% This MATLAB program tests the function read_barcode.

% Octave-specific commands
is_octave = exist('OCTAVE_VERSION', 'builtin') ~= 0;
if is_octave
  pkg load signal;
end

clear;
close all;
clc;

barcode_values = [ ...
    'A' 'B' 'C' 'D' ...
    'E' 'F' 'G' 'H' ...
    'I' 'J' 'K' 'L' ...
    'M' 'N' 'O' 'P' ];
barcode_keys = [ ...
   311113113 113113113 313113111 111133113 ...
   311133111 113133111 111113313 311113311 ...
   113113311 111133311 311111133 113111133 ...
   313111131 111131133 311131131 113131131 ];

barcodes = {
    'sample-barcode-pics/letter_A_noisy.jpg' ...
    'sample-barcode-pics/letter_B_noisy.jpg' ...
    'sample-barcode-pics/letter_C_noisy.jpg' ...
    'sample-barcode-pics/letter_D_noisy.jpg' ...
    'sample-barcode-pics/letter_E_noisy.jpg' ...
    'sample-barcode-pics/letter_F_noisy.jpg' ...
    'sample-barcode-pics/letter_G_noisy.jpg' ...
    'sample-barcode-pics/letter_H_noisy.jpg' ...
    'sample-barcode-pics/letter_I_noisy.jpg' ...
    'sample-barcode-pics/letter_J_noisy.jpg' ...
    'sample-barcode-pics/letter_K_noisy.jpg' ...
    'sample-barcode-pics/letter_L_noisy.jpg' ...
    'sample-barcode-pics/letter_M_noisy.jpg' ...
    'sample-barcode-pics/letter_N_noisy.jpg' ...
    'sample-barcode-pics/letter_O_noisy.jpg' ...
    'sample-barcode-pics/letter_P_noisy.jpg' ...
    ...
    'sample-barcode-scans/input_letter_A_large_backwards.csv' ...
    'sample-barcode-scans/input_letter_A_large_forwards.csv' ...
    'sample-barcode-scans/input_letter_A_medium_backwards.csv' ...
    'sample-barcode-scans/input_letter_A_medium_forwards.csv' ...
    'sample-barcode-scans/input_letter_K_medium_backwards.csv' ...
    'sample-barcode-scans/input_letter_K_medium_forwards.csv' ...
    };

tests = 0;
failures = 0;

for i = 1:numel(barcodes)
    tests = tests + 1;
    code = read_barcode(barcodes{i});
    index = find(barcode_keys == code);
    if isempty(index)
        index = find(barcode_keys == str2num(fliplr(num2str(code))));
    end
    if isempty(index)
      failures = failures + 1;
      fprintf('[FAILURE] Testing file: %s | Barcode not found.\n', barcodes{i});
    else
      fprintf( ...
          '[SUCCESS] Testing file: %s | Barcode: %s\n', ...
          barcodes{i}, barcode_values(index) ...
      );
    end
end

fprintf('\n');
fprintf('[INFO   ] --------------------------------------------------------\n');
if failures == 0
  fprintf('[INFO   ] TEST SUITE PASSED\n');
else
  fprintf('[INFO   ] TEST SUITE FAILED\n');
end
fprintf('[INFO   ] --------------------------------------------------------\n');
fprintf('[INFO   ] %d tests run.\n', tests);
fprintf('[INFO   ] %d tests failed.\n', failures);
fprintf('[INFO   ] --------------------------------------------------------\n');
fprintf('\n');