# This YAML file configures Travis CI to build and test the projects.

sudo: required

language: c

notifications:
  email:
    on_success: change
    on_failure: always

services:
  - docker

before_install:
  - docker run -dt -p 127.0.0.1:80:80 jleung51/octave:0.2 /bin/bash
  - docker ps -a
  - CONTAINER="$(docker ps -a --format '{{.Names}}')"
  - docker cp project-3-barcode-scanner/ ${CONTAINER}:./

script:
  - make activate_dummy all clean deactivate_dummy
  - docker exec -t ${CONTAINER} /bin/sh -c "cd project-3-barcode-scanner/matlab/ && octave --no-gui testreadbarcode.m"
