# Bitbucket Pipelines configuration file

image: jleung51/octave:0.2

options:
  max-time: 9

pipelines:
  default:
    - step:
        name: Compile all ROBOTC files
        script:
          - ./use_robotc_dummy_code.sh
          - make all clean
    - step:
        name: Project 3 Barcode Scanner - Tests
        script:
          - cd project-3-barcode-scanner/matlab/
          - octave --no-gui testreadbarcode.m
          - cd ../
