# Bitbucket Pipelines configuration file

image: atlassian/default-image:1

options:
  max-time: 5

pipelines:
  default:
    - step:
        name: Project 3: Barcode Scanner - Tests
        script:
          - sudo add-apt-repository ppa:octave/stable
          - sudo apt-get update
          - sudo apt-get install -y octave liboctave-dev
          - octave --no-gui pkg install -forge control
          - octave --no-gui pkg install -forge signal
          - cd project-3-barcode-scanner/
          - octave --no-gui test_read_barcode.m
          - cd ../
