#pragma config(Sensor, S3,     ColorSensor,    sensorEV3_Color)
#pragma config(Sensor, S4,     UltrasonicSensor, sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          LeftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          RightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	// if greater than 40, WHITE
	int reflectionThreshold = 40;
	int speed = 15;
	
	setMotorSpeed(LeftMotor, speed);
	setMotorSpeed(RightMotor, speed);
	
	while(getColorReflected(ColorSensor) > reflectionThreshold) {
	}
	
	while (true) {
	
		int colorReflected = getColorReflected(ColorSensor);
	
		displayCenteredTextLine(5, "%d", colorReflected);
		
		
		if (colorReflected < reflectionThreshold){
			setMotorSpeed(LeftMotor, -speed);
			setMotorSpeed(RightMotor, speed);
		} else {
			setMotorSpeed(LeftMotor, speed);
			setMotorSpeed(RightMotor, -speed);
		}
	}
}